### ISSUE TITLE
Email banner is sliding with the screen when scrolling

### ISSUE THREAD

**Issue by HexTree** [HexTree/CoffeePoints#26]
Sometimes when I scroll, the green group email scrolls with the page. It's a bit odd. I've only tried in the emulator.

![banner](https://cloud.githubusercontent.com/assets/7933725/21958613/33c8394e-dac3-11e6-8067-5ede1b992982.png)

**Comment by 7mTo** [comment]
This appears at every single page that is longer than the height of the device and it's triggered by pressing on the page once. If you press it again it would go back down. Might be related to a css script that is designed for an input footer. **Check the classes of the footer**.

**Comment by 7mTo** [comment]
This is a feature that went wrong with our project.

**Comment by 7mTo** [comment]
Removed footer
