### ISSUE TITLE
Scanner permissions 'don't ask again' checkbox question

### ISSUE THREAD

**Issue by HexTree** [HexTree/CoffeePoints#32]
(Pasted from Slack discussion)

@7mto, when you go to the scan menu, it asks for permission to take pictures and record video. When you check the 'don't ask again' box, the 'Allow' button is greyed out, means you can only choose to always deny in future. This is a problem, because if someone checks the box and Denies access, then every time they go to the Scan menu it will deny access. I'm not sure how they will re-enable access to the camera if they want to scan. 

If anything it should be the other way round, they should be able to give permanent access for the app to take pictures, so that they don't have to answer the dialog every time. Going through the dialog every time is bothersome and the scanning ceases to be a nice 'one-click' feature.

Do we have the ability to change this? Or is this dialog box built into the package?

**Comment by 7mTo** [comment]
The dialog is by the Android system not our app. That's their problem. We are not here to baby sit users. If they want to reset the permission, they can by resetting the app settings from Settings->Apps->Sustainability. If they don't check the box "which does not exist on my phone", it's their problem.

We can add that information to the help page but that's it for me. What do you think?

**Comment by HexTree** [comment]
Ok. If I accidentally pressed the checkbox I would have had no idea how to bring it back up, and likely some people will not be familiar with apps. I'll add that information to the help page.
