### ISSUE TITLE
Apple Rejection - resolve feedback

### ISSUE THREAD

**Issue by HexTree** [HexTree/CoffeePoints#39]
New message from Apple:

*************

We noticed that your app or its metadata includes irrelevant third-party platform information. Specifically, Google Play is mentioned in the app.

Referencing third-party platforms in your app or its metadata is not permitted on the App Store unless there is specific interactive functionality.

Please see attached screenshots for details.

Next Steps

Please remove all instances of this information from your app and its metadata, including the app description, What's New info, previews, and screenshots.

Since your iTunes Connect status is Rejected, a new binary will be required. Make the desired metadata changes when you upload the new binary.

NOTE: Please be sure to make any metadata changes to all app localizations by selecting each specific localization and making appropriate changes.

Business - 3.1.4

Your app enables additional features or functionality when used with QR code. However, these features are not completely dependent on QR code and are unavailable to users without the QR code.

Next Steps

Please provide a means to access these additional features from within the app. Alternatively, you may revise your app to ensure the additional features are completely dependent on the approved accessory. 

*************

**Comment by HexTree** [comment]
It seems that we should remove mention of Google Play altogether from the poster. Or maybe the whole 'Download app' step. I'm not sure why it was there, come to think of it, since the user has already downloaded the app.

As for the QR code feedback, I'm not sure what they are getting at exactly. I expect they are talking about scanning the ID card at the start. We should make it so that you can clearly choose to enter your id by hand instead of scanning.

**Comment by 7mTo** [comment]
Remove google auth functions from id.js and from any commented meta data

**Comment by yipcma** [comment]
would this work? https://github.com/EddyVerbruggen/cordova-plugin-googleplus

**Comment by HexTree** [comment]
Not really, we didn't want to have people log in via Google, because not necessarily everyone has an account to log in with. And also Apple doesn't seem to like having any kind of sign-in to use the app.
